### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'addInstructions'

### ISSUE THREAD

**Issue by paulz** [CapeLeidokos/elf_diff#5]
Seem like a great utility, unfortunately unable to use due to this error:

```
elf_diff --old one.elf  --new two.elf  
bin_path = .../elf_diff/bin
bin_path = .../elf_diff/bin
Traceback (most recent call last):
  File ".../elf_diff/bin/elf_diff", line 52, in <module>
    generatePairReport(settings)
  File ".../elf_diff/bin/../python/elf_diff/pair_report.py", line 405, in generatePairReport
    PairReport(settings).generate()
  File ".../elf_diff/bin/../python/elf_diff/pair_report.py", line 38, in __init__
    settings.new_binary_filename)
  File ".../elf_diff/bin/../python/elf_diff/binary_pair.py", line 41, in __init__
    self.old_binary = Binary(self.settings, self.old_binary_filename)
  File ".../elf_diff/bin/../python/elf_diff/binary.py", line 44, in __init__
    self.parseSymbols()
  File ".../elf_diff/bin/../python/elf_diff/binary.py", line 139, in parseSymbols
    cur_symbol.addInstructions(instruction_line_match.group(1) + instruction_line_match.group(2))
AttributeError: 'NoneType' object has no attribute 'addInstructions'
```

`conda list:`

```
# Name                    Version                   Build  Channel
ca-certificates           2020.10.14                    0  
certifi                   2019.11.28               py27_0  
jinja2                    2.11.2                   pypi_0    pypi
libcxx                    10.0.0                        1  
libedit                   3.1.20191231         h1de35cc_1  
libffi                    3.3                  hb1e8313_2  
markupsafe                1.1.1                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
pdfkit                    0.6.1                    pypi_0    pypi
pip                       19.3.1                   py27_0  
python                    2.7.18               h47d645e_1  
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h1de35cc_0  
setuptools                44.0.0                   py27_0  
sqlite                    3.33.0               hffcf06c_0  
tk                        8.6.10               hb0a8c7a_0  
wheel                     0.35.1                     py_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by noseglasses** [comment]
I know, this has been hanging around for ages. Now I am trying to fix the problem but cannot reproduce it. Could someone who is facing the same problem please provide two elf files for which the tool fails as reported. The simpler and smaller the files, the better. Also, please provide platform and compiler info.

**Comment by paulz** [comment]
[main.elf.zip](https://github.com/CapeLeidokos/elf_diff/files/6958806/main.elf.zip)

```
bin/elf_diff --old main.elf --new main.elf 
bin_path = <mypath>/elf_diff/bin
bin_path = <mypath>/elf_diff/bin
Writing html file elf_diff_pair_report.html
Traceback (most recent call last):
  File "bin/elf_diff", line 52, in <module>
    generatePairReport(settings)
  File "<mypath>/elf_diff/bin/../python/elf_diff/pair_report.py", line 405, in generatePairReport
    PairReport(settings).generate()
  File "<mypath>/elf_diff/bin/../python/elf_diff/report.py", line 39, in generate
    self.writeHTML(f)
  File "<mypath>/elf_diff/bin/../python/elf_diff/report.py", line 59, in writeHTML
    keywords = self.configureJinjaKeywords(skip_details)
  File "<mypath>/elf_diff/bin/../python/elf_diff/pair_report.py", line 342, in configureJinjaKeywords
    ,"code_size_old_overall" : str(old_binary.progmem_size)
AttributeError: 'Binary' object has no attribute 'progmem_size'
```

macOS with [GNU Arm Embedded Toolchain](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm)

```
/Applications/ARM/arm-none-eabi/bin/readelf -h main.elf
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x255
  Start of program headers:          52 (bytes into file)
  Start of section headers:          287012 (bytes into file)
  Flags:                             0x5000200, Version5 EABI, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         3
  Size of section headers:           40 (bytes)
  Number of section headers:         16
  Section header string table index: 15

```

**Comment by paulz** [comment]
would be nice if CI workflow run elf-diff and produce expected report from pre-existing elf

**Comment by noseglasses** [comment]
I applied several fixes today. On my Ubuntu-machine using package binutils-arm-linux-gnueabi I cannot reproduce your problem, unfortunately.

Could you please try again with the latest version and post the tool output if the problem persists.

Regarding the CI: This project was using Travis CI before to do the type of testing you suggested. But the CI integration broke some time in the past. Now I switched to a Github workflow with integrated testing, which works like a charm. The CI performs some typical report creation runs and also some basic unit-testing.

See here: https://github.com/CapeLeidokos/elf_diff/runs/3288189090

**Comment by noseglasses** [comment]
Ok, btw. I forgot to mention that I changed the lookup behavior of the binutils. Now you can either use the PATH variable to define an alternative location or explicitly define command names like `--objdump_command ...`. Search order is explicit command names -> bin_dir -> PATH.

I just mention this because you might suffering a command lookup problem. In some cases it happend that the wrong objdump/nm/size command was used.

**Comment by noseglasses** [comment]
The project has evolved quite a lot since this issue was filed.
I'm closing this issue for now due to a lack of feedback. Please feel free to reopen if necessary if the problems persist.
